import Head from "next/head";
import { Flex, Input, Select, Box } from "@chakra-ui/react";
import { Header } from "./../components/Header/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lab Coodesh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box
       
        h="100vh"
        w="100%"
      >
        <Header />
        <Flex
          mx="auto"
          mt="50px"
          justifyContent="space-around"
          w="620px"
          h="200px"
        >
          <Input w="400px" />
          <Select w="180px">
            <option>mais relevante</option>
            <option>menos relevante</option>
          </Select>
        </Flex>
      </Box>
    </>
  );
}
