import Head from "next/head";
import {
  Flex,
  Input,
  Select,
  Box,
  Image,
  Button,
  Grid,
  GridItem,
  Text,
  Heading,
  CardBody,
  Card,
  Stack,
  Divider,
  Spinner,
  Center,
} from "@chakra-ui/react";
import { Header } from "./../components/Header/index";
import axios from "axios";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { baseUrl } from "./../assets/baseUrl";

export default function Home({ dados }) {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();
  const [infos, setInfos] = useState([]);
  const [searchInput, setSearchInput] = useState("");
  const [relevance, setRelevante] = useState(true);
  const [loadingSearch, setLoadingSearch] = useState(false);
  console.log("teste dados dados", infos);
  const quantidade = infos.length;

  useEffect(() => {
    setInfos(dados);
  }, []);

  const onSubmit = async () => {
    console.log("testes", searchInput, relevance);
    try {
      setLoadingSearch(true);
      if (relevance) {
        const response = await axios.get(
          `${baseUrl}/wp-json/mc/v2/posts?search=${searchInput}&page=1&orderby=relevance`
        );
        const data = response.data;
        console.log("teste dados", data.data);
        setInfos([...data.data]);
        setLoadingSearch(false);
      } else {
        const response = await axios.get(
          `${baseUrl}/wp-json/mc/v2/posts?search=${searchInput}`
        );
        const data = response.data;
        console.log("teste dados", data.data);
        setInfos([...data.data]);
        setLoadingSearch(false);
      }
    } catch (error) {
      console.log(error);
      setLoadingSearch(false);
    }
  };

  return (
    <>
      <Head>
        <title>Lab Coodesh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box h="100vh" w="100%">
        <Header />
        <Flex
          mx="auto"
          mt="30px"
          justifyContent="space-around"
          w="700px"
          h="200px"
        >
          <Input
            onChange={(e) => setSearchInput(e.target.value)}
            name="buscar"
            type="text"
            w="400px"
            onKeyPress={onSubmit}
          />
          <Button onClick={onSubmit}>Buscar</Button>
          <Select
            onChange={(e) => setRelevante(e.target.value)}
            name="relevante"
            variant="flushed"
            w="180px"
          >
            <option value={true}>mais relevante</option>
            <option value={false}>menos relevante</option>
          </Select>
        </Flex>
        {loadingSearch ? (
          <Center h="100px" w="100%">
            <Spinner />
          </Center>
        ) : (
          <>
            <Text ml="1%" position="relative" top="-135px" h="20px">
              {quantidade} artigos encontrados.
            </Text>

            <Grid
              position="relative"
              top="-120px"
              templateColumns="repeat(4, 1fr)"
              gap={8}
            >
              {infos.map((dado) => {
                return (
                  <>
                    {/* onClick={dado.link} */}
                    {dado.length === 0 || dado === null ? (
                      <Text>
                        Não existem artigos relacionados ao termo pesquisado!
                      </Text>
                    ) : (
                      <>
                        <GridItem mb="20px" mx="auto" w="95%" h="380px">
                          <Card key={dado.id} maxW="sm" h="380px">
                            <CardBody>
                              {dado.featured_media?.large == null ? (
                                <Center w="100%" h="175px">
                                  <Spinner />
                                </Center>
                              ) : (
                                <Image
                                  objectFit="cover"
                                  src={
                                    dado.featured_media?.large === null
                                      ? "https://images.unsplash.com/photo-1531403009284-440f080d1e12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"
                                      : dado.featured_media?.large
                                  }
                                  borderRadius="sm"
                                  alt={dado.title}
                                />
                              )}

                              <Stack mt="6" spacing="3">
                                <Heading size="sm">{dado.title}</Heading>
                                <Text>{dado.title}</Text>
                              </Stack>
                            </CardBody>
                            <Divider />
                          </Card>
                        </GridItem>
                      </>
                    )}
                  </>
                );
              })}
            </Grid>
          </>
        )}
      </Box>
    </>
  );
}

export const getServerSideProps = async () => {
  const url = "https://beta.mejorconsalud.com/wp-json/mc/v1/posts";

  try {
    let response = await axios.get(url);
    const data = response.data;
    return {
      props: { dados: data },
    };
  } catch (error) {
    console.log(error);
  }
};
