import Head from "next/head";
import {
  Flex,
  Input,
  Select,
  Box,
  Button,
  Text,
  Spinner,
  Center,
} from "@chakra-ui/react";
import { Header } from "./../components/Header/index";
import axios from "axios";
import { useEffect, useState } from "react";
import { baseUrl } from "./../assets/baseUrl";
import dynamic from "next/dynamic";

export default function Home({ dados }) {
  const [infos, setInfos] = useState([]);
  const [searchInput, setSearchInput] = useState("");
  const [relevance, setRelevante] = useState(true);
  const [loadingSearch, setLoadingSearch] = useState(false);
  console.log("teste dados dados", infos);
  const quantidade = infos.length;

  useEffect(() => {
    setInfos(dados);
  }, []);

  const onSubmit = async () => {
    console.log("testes", searchInput, relevance);
    try {
      setLoadingSearch(true);
      if (relevance) {
        const response = await axios.get(
          `${baseUrl}/wp-json/mc/v2/posts?search=${searchInput}&page=1&orderby=relevance`
        );
        const data = response.data;
        console.log("teste dados", data.data);
        setInfos([...data.data]);
        setLoadingSearch(false);
      } else {
        const response = await axios.get(
          `${baseUrl}/wp-json/mc/v2/posts?search=${searchInput}`
        );
        const data = response.data;
        console.log("teste dados", data.data);
        setInfos([...data.data]);
        setLoadingSearch(false);
      }
    } catch (error) {
      console.log(error);
      setLoadingSearch(false);
    }
  };

  return (
    <>
      <Head>
        <title>Lab Coodesh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box minH="calc(100vh - 60px)" w="100%">
        <Header />
        <Flex
          mx="auto"
          mt="30px"
          justifyContent="space-around"
          w="700px"
          h="200px"
        >
          <Input
            onChange={(e) => setSearchInput(e.target.value)}
            name="buscar"
            type="text"
            w="400px"
            onKeyPress={onSubmit}
          />
          <Button colorScheme="teal" onClick={onSubmit}>
            Buscar
          </Button>
          <Select
            onChange={(e) => setRelevante(e.target.value)}
            name="relevante"
            variant="flushed"
            w="180px"
          >
            <option value={true}>mais relevante</option>
            <option value={false}>menos relevante</option>
          </Select>
        </Flex>
        {loadingSearch ? (
          <Center h="100px" w="100%">
            <Spinner />
          </Center>
        ) : (
          <>
            <Text ml="1%" position="relative" top="-135px" h="20px">
              {quantidade} artigos encontrados.
            </Text>
            <MyDynamicComponent infos={infos} />
          </>
        )}
      </Box>
    </>
  );
}

export const getServerSideProps = async () => {
  const url = "https://beta.mejorconsalud.com/wp-json/mc/v1/posts";

  try {
    let response = await axios.get(url);
    const data = response.data;
    return {
      props: { dados: data },
    };
  } catch (error) {
    console.log(error);
  }
};

const MyDynamicComponent = dynamic(() => import("../components/Grid"), {
  loading: () => <p>Loading...</p>,
  ssr: false,
});
